import { Link } from "react-router-dom";
import PublicLayout from "../components/PublicLayout";
import Icon from "../components/Icon";

export default function TeacherTools() {
  return (
    <PublicLayout title="CGBSE Teacher AI Tools for Planning | VidyaAI" description="Explore VidyaAI tools for CGBSE teachers: editable curriculum plans, lesson plans, Hindi question papers, chapter selection and model-paper resources." path="/cgbse-teacher-tools">
      <section className="resource-hero public-section"><p className="public-eyebrow">VIDYAAI FOR CGBSE TEACHERS</p><h1>Teacher planning tools with the teacher in control</h1><p>Turn selected classes, subjects, chapters and assessment requirements into editable teaching resources. VidyaAI helps with the first draft; the teacher reviews, corrects and decides what reaches the classroom.</p><div className="public-hero-actions"><Link className="public-primary-button" to="/login">Open teacher workspace <Icon name="arrowRight" size={18} /></Link><Link className="public-secondary-button" to="/cgbse-class-10-model-papers">Browse source papers</Link></div></section>
      <section className="seo-split public-section"><div><p className="public-eyebrow">CURRICULUM CREATOR</p><h2>Plan the teaching sequence</h2><p>Select the class, subject and chapters, then draft a week-wise plan with learning outcomes, classroom activities, assessment opportunities and revision. Every generated plan is a working document: teachers can change the pace, remove unsuitable material and add their own instructions.</p></div><div><p className="public-eyebrow">LESSON PLANNER</p><h2>Prepare a teachable lesson</h2><p>Build a lesson around the topic, available time and classroom need. The result can organise objectives, explanations, activities, checks for understanding and follow-up practice so the teacher has a coherent starting point instead of a blank page.</p></div></section>
      <section className="seo-grounding public-section"><div><p className="public-eyebrow">QUESTION PAPER CREATOR</p><h2>Create a printable Hindi question paper</h2></div><div><p>Choose chapters and define the paper structure section by section: question type, count, marks per question, word limit and custom questions. VidyaAI uses curriculum and model-paper context where available, then presents the draft in a paper-style preview for review and download.</p><p>Before distribution, verify every question, option, answer key, total mark and chapter mapping. AI-generated assessments are drafts and are not official CGBSE publications.</p></div></section>
      <section className="seo-resource-note public-section"><h2>A responsible workflow for generated resources</h2><ol><li>Choose only the chapters learners have studied.</li><li>Give specific instructions for language, difficulty and question types.</li><li>Review facts, marks, repetition and accessibility.</li><li>Edit the draft to match your learners and school expectations.</li><li>Download the final version only after professional review.</li></ol><p>Read the <Link to="/ai-use">Responsible AI Use Policy</Link> for accuracy limits and teacher responsibilities.</p></section>
    </PublicLayout>
  );
}
